version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 333965lq
      MYSQL_DATABASE: legym
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    command: >
      sh -c "aerich upgrade && 
             uvicorn backend.main:app --host 0.0.0.0 --port 8000 & 
             python backend/app/runTask/runMain.py"
    volumes:
      - ./fastapi:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - fastapi
      - vue3

   vue3:
     build:
       context: .
       dockerfile: vue3/Dockerfile
     ports:
       - "80:80"
     depends_on:
       - fastapi
volumes:
  db_data:
