version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 333965lq
      MYSQL_DATABASE: legym
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    command: bash -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000 & python backend/app/runTask/runMain.py"
    volumes:
      - ./fastapi:/app
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:333965lq@mysql:3306/legym

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./vue3/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - fastapi

volumes:
  mysql_data:
