version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 333965lq
      MYSQL_DATABASE: legym
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  fastapi:
    build:
      context: ./fastapi/backend
      dockerfile: Dockerfile
    command: >
      sh -c "aerich upgrade && 
             uvicorn main:app --host 0.0.0.0 --port 8000 &&
             python runTask/runMain.py"
    volumes:
      - ./fastapi/backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  vue:
    build:
      context: ./vue3
      dockerfile: Dockerfile
    volumes:
      - ./vue3/dist:/usr/share/nginx/html
    depends_on:
      - fastapi

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vue

volumes:
  db_data:
