version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi/backend
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 & python app/runTask/runMain.py"  # 修改路径
    volumes:
      - ./fastapi/backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  vue:
    build:
      context: ./vue3
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - fastapi

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - vue

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 333965lq
      MYSQL_DATABASE: legym
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
