version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 333965lq
      MYSQL_DATABASE: legym
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./fastapi/backend
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 &
             python runTask/runMain.py"
    volumes:
      - ./fastapi/backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:333965lq@db:3306/legym

  frontend:
    build: ./vue3
    ports:
      - "80:80"
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  db_data:
