version: '3.8'

services:
  backend:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:333965lq@mysql/legym
    command: ["sh", "-c", "aerich upgrade && uvicorn backend.main:app --host 0.0.0.0 --port 8000 & python backend/app/runTask/runMain.py"]
    networks:
      - app-network

  frontend:
    build:
      context: ./vue3
      dockerfile: Dockerfile
    container_name: vue3-frontend
    ports:
      - "8080:80"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 333965lq
      MYSQL_DATABASE: legym
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
